include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

.default_properties:
  image: node:22.10.0-alpine3.20
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key:
      files:
        - package-lock.json
        - prisma/prisma.schema
      prefix: $CI_RUNNER_EXECUTABLE_ARCH-$CI_JOB_IMAGE
    paths:
      - .npm

lint:
  extends: .default_properties
  script:
    - SKIP_VALIDATION=1 npm run lint

prettier:
  extends: .default_properties
  script:
    - npx prettier --check .

test:
  extends: .default_properties
  script:
    - npm run test

build:
  extends: .default_properties
  script:
    - SKIP_VALIDATION=1 npm run build
