# include:
#   - template: Jobs/SAST.gitlab-ci.yml
#   - template: Jobs/Secret-Detection.gitlab-ci.yml

.default_properties:
  image: node:22.11.0-bookworm
  before_script:
    - npm ci --cache .npm --prefer-offline
  cache:
    key:
      files:
        - package-lock.json
        - prisma/prisma.schema
      prefix: $CI_RUNNER_EXECUTABLE_ARCH-$CI_JOB_IMAGE
    paths:
      - .npm

.vars: &vars
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/db

build:
  extends: .default_properties
  stage: build
  variables:
    <<: *vars
  script:
    - npm run build
  artifacts:
    paths:
      - .next/
    expire_in: 1 hour

lint:
  extends: .default_properties
  stage: test
  script:
    - SKIP_VALIDATION=1 npm run lint

prettier:
  extends: .default_properties
  stage: test
  script:
    - npx prettier --check .

test:
  extends: .default_properties
  stage: test
  script:
    - SKIP_VALIDATION=1 npm run test

playwright:
  extends: .default_properties
  image: mcr.microsoft.com/playwright:v1.48.2-noble
  services:
    - postgres
  variables:
    <<: *vars
    POSTGRES_PASSWORD: postgres
    HOSTNAME: 0.0.0.0
  script:
    - cd playwright
    - npm ci
    - npx prisma generate --schema=../prisma/schema.prisma --generator=playwrightClient
    - npx prisma db push --schema=../prisma/schema.prisma
    - npx playwright test
  artifacts:
    paths:
      - playwright/playwright-report/
