services:
  postgres:
    image: postgres:17.5-alpine3.20
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  maildev:
    image: maildev/maildev:2.2.1
    restart: on-failure
    environment:
      - TZ=Europe/Berlin
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - 1080:1080
      - 1025:1025
