name: Validate app

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4.0.2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('.nvmrc', 'package-lock.json', 'prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint
        run: npm run lint
        continue-on-error: true
        env:
          SKIP_VALIDATION: "1"

  prettier:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4.0.2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('.nvmrc', 'package-lock.json', 'prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Prettier
        run: npx prettier --check .
        continue-on-error: true

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4.0.2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('.nvmrc', 'package-lock.json', 'prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Test
        run: npm run test

  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4.0.2
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('.nvmrc', 'package-lock.json', 'prisma/prisma.schema') }}

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Test
        run: npm run build
        env:
          SKIP_VALIDATION: "1"
